### ISSUE TITLE
invalid "autosave" causes settings to fail loadin

### ISSUE THREAD

**Issue by mentalinc** [BlueBlock/Elucidate#1]
Set "autosave " to another larger than 1024 and results in an error saying value is not valid.
But doesn't show what a valid range is and stops the loading of any other GUI items for settings.

Needed to edit the setting to find something that worked. not sure where the 1024 value is documented as the max

**Comment by BlueBlock** [comment]
I'll correct the check and exception.

I've looked and tested very high int's for autosave in snapraid and I'm hitting any specified limit.
autoave is in GB's so it doesn't seem practical to have it much higher than 1024, but I'll set the autosave limit to be max int since snapraid currently accepts it.
